### ISSUE TITLE
POE Sniper Questions

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#1]
Hey Licoffe,

Very nice app, I typically play poe with about 70 poe.trade windows open (and I really only stop there because it starts to get out of hand).  I've been trying to find something exactly like this for a few months now.  The UI is also clean and immediately comprehensible, overall the app is phenomenal, thank you.  I've had a few questions and QoL suggestions, hopefully you don't mind hearing outside perspectives/requests.

1) I have downloaded both the source and the release.  I have been able to launch and run the release successfully but not the source.  I tried two ways.  First I attempted to follow your directions by opening a terminal (windows start button, "cmd" <enter> and cloning the code using the git command.  I received an error message that git is not a recognized command.  Second I attempted to skip the git portion by downloading the code folder onto my computer, then changing to the directory where I have the code stored"cd C:\Users\Home\Desktop\POE Apps\POE-sniper-master-licoffe".  The cd was successful but typing "npm install" resulted in an error message "'npm' is not recognized as an internal command, operable program or batch file."

At this point I am stuck on trying to launch the release.  Perhaps "terminal" does not mean command prompt?  Maybe I need some tools like a compiler or somethign to be directly running the javascript?

2) Just a question.  I see that when I close and re-open the release app my searches are being saved, but I can't figure out where (on the release or the source) the searches are being saved.  I don't really have a reason besides curiosity and the fact that I haven't been able to find it for asking this.

3) Do you have any plans to add pseudo mods?  Res is probably the most challenging mod to search on without pseudo mods.

4) A global option for clipboard would be nice.  I assume that I will pretty much always want it completely on (most of the time) or completely off (running lab).

5) Gem Experience: I know that the api provides gem experience.  Being able to search on Gem Experience would be a nice sniping bonus, especially early on in the league.

6) Is there a way for me to modify the whisper message in the release version?  I found it in the source but as I mentioned earlier, I haven't been able to launch that yet.

That's all I can think of right now.  Thanks for any answer you can provide.

**Comment by licoffe** [comment]
Hi gdneye,

I'm really glad you enjoy the tool so far. 

1. It seems I omitted some instructions in the README. To run the tool from source, you will need to install [NodeJs](https://nodejs.org/en/) beforehand and optionally `git`. Of course this is not really necessary if all you want is to run the tool in its current state. However, if you want to tweak the code to add your own features, running from sources is the way to go.

2. Every time, a filter is added/edited/removed, the current state of all the filters is written to disk inside **poe-sniper\resources\app\filters.json** :)

3. I guess that's the next big feature to add after fixing the current issues.

4 & 6. Eventually, I planned to add a settings window which would allow to tweak several parameters of the tool, such as the sound file used, the sound volume, the message copied to the clipboard, etc. These parameters are not hardcoded and you can tweak them manually inside the **poe-sniper\resources\app\config.json** file for now.

5. That should be pretty easy to do. I just have to find a place for it in the current layout. I could split the Tier input in two to leave space for experience. 

Thank you for this thorough feedback :)

**Comment by gdneye** [comment]
Thanks for the quick answers.  I'll install NodeJs when I get home and try that out.  If you need any assistance (with testing or w/e) let me know, I'd be happy to help.
