### ISSUE TITLE
Linked filters issue

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#15]
This seemed pretty straightforward.  I downloaded the newest release (freshly because I had previously attempted to copy my filters.json file over and wanted to make sure I was starting 100% clean).  Once I loaded it I started re-entering my filters and ran into a problem when I hit the Goldwyrm's.  The only thing I can think of that I might have done was moving too quickly (prior to the video).  I've noticed sometimes that if I don't wait after adding a filter for the poe.trade stats to fully load before doing my next thing it often causes issues.

https://youtu.be/jWNW874ThR4

**Comment by gdneye** [comment]
After removing all filters and attempting to restart the program I received the following error message, most likely related to the initial error.
![fdsafdsa](https://user-images.githubusercontent.com/26702989/27394916-9c000420-5673-11e7-9005-95b7a8d956b0.png)

**Comment by licoffe** [comment]
That last issue may be different since it's related to the config.json file. I had this error once and that was because several instances of POE-sniper were running at the same time, writing the same file all together and causing corruption. If you check your task manager, you will probably notice several poe-sniper processes running.

**Comment by licoffe** [comment]
I will check for the filter bug again. Each filter is normally given a unique id, but in some buggy case, two filters get the same id, which links them together. I'm not quite sure how this happens though, but I'll figure it out.

**Comment by licoffe** [comment]
So, when clicking a filter for edition, the tool would store the id of the edited filter in a global var. Each time when adding a new filter, the tool checks if this global var contains an id or if it's empty. If there's an id, it would associate it to the new filter. This is useful when editing filters. However, when cancelling edition, the global var was not reset and still contained another filter id, causing errors. I'll upload a video showing the issue.

EDIT: [Video](https://www.youtube.com/watch?v=EE4PhqOUpE8)

**Comment by licoffe** [comment]
It should be fixed in the last update
