### ISSUE TITLE
Question - Underpriced Feature

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#20]
Hey Licoffe,

Thanks for continuing to improve the sniper.  I'm just wondering how the "Underpriced" option works.  Is it looking at the items you have filters set up for and underpricing only those items?  Or is it underpricing all items in the league.  I assume its closer to the first as the second one seems impractical from a programming perspective.

**Comment by licoffe** [comment]
Hey Gdneye,

For the "Underpriced" option, I am using the poe-rates.com backend to get stats (min, median, mode) on various items. If an item appears in the stream with a price lower than X% based on one of the metrics (min, mode, etc...) I send a notification.
