### ISSUE TITLE
Latest Update

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#21]
It appears that the latest update may have created some issues with functions that were previously working.

I've been unable to get the "settings" or "Import filter" buttons to work.  Also, previously when I moved the slider from "filters" to "underpriced" it would auto collapse the filters and it no longer does this (this last one may have been intentional).

https://youtu.be/7ddmLi6a_lc

Thanks,
Gdneye

**Comment by licoffe** [comment]
Thanks a lot for reporting, I'm looking into it. I'm using the tool on a different platform and sometimes everything does not work as intended for each of the platforms.

**Comment by licoffe** [comment]
Looks like it was just a packaging issue, I'm reuploading the release. It should be safe to download in 10 min.

**Comment by gdneye** [comment]
Thanks!
