### ISSUE TITLE
Fails to get nextchangeid

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#22]
Occasionally the app has issues moving to the nextchangeid.

I am unsure what causes the issue.

https://youtu.be/_dPIVLILYCI

**Comment by licoffe** [comment]
Thanks for reporting, I'll upload a fix soon!

**Comment by licoffe** [comment]
The issue should be fixed now.

**Comment by gdneye** [comment]
Thanks!

**Comment by licoffe** [comment]
You're welcome! Thanks for reporting :)
