### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by samuliz** [licoffe/POE-sniper#23]
When I click the item message pops up in the toolbar to indicate that the trade message is copied to the clipboard but it does not do that. Any ideas why this is happening? I love your project but I really can't use it if I can't message anyone...

**Comment by licoffe** [comment]
Could you tell me which OS you're using and the version of the tool?

**Comment by 8532** [comment]
hi i have exact the same problem :-(
I have windows 10 and the new version.
