### ISSUE TITLE
Missing Affix

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#25]
The affix "% increased maximum energy shield" is missing.

Thanks,
Gdneye

**Comment by gdneye** [comment]
Also, "% more Melee Physical Damage during effect" from Lion's Roar.

**Comment by licoffe** [comment]
I added the Lion's Roar affixes as none of them were in the tool. However, are you sure that there is a "% increased maximum energy shield" affix. I already have "% increased energy shield", isn't this the same?

**Comment by gdneye** [comment]
Thanks... the affix I'm looking at occurs on the "Energy From Within" Jewel.

https://pathofexile.gamepedia.com/Energy_From_Within

Looking at a couple of poe.trade searches it appears that there is a difference between the two affixes, but I'm not exactly sure what it is.

http://poe.trade/search/asihagutebokik
http://poe.trade/search/oyurunamunigas

**Comment by licoffe** [comment]
Oh I see, one is local to the item, the other one adds on top of the ES pool :)

**Comment by licoffe** [comment]
That's why it's a 1 exa craft on the master bench :D

**Comment by gdneye** [comment]
=).  Thanks for adding those two.  I've found another one, "Increased damage over time during flask effect" from witchfire brew.  Is it easier for you if I close out the current ticket (since you added each of those) and open new tickets each time I find a missing affix?  Or is it easier if I list all missing affixes in one thread and leave it open?

Also, are the filters on your app case sensitive?  I can add filters in manually in between updates but not sure how careful I need to be when adding them.

Thanks!

**Comment by gdneye** [comment]
One more

15% increased Area of Effect while Unarmed

from Martial Artistry Crimson Jewel

**Comment by licoffe** [comment]
> =). Thanks for adding those two

You're welcome! :)

> Is it easier for you if I close out the current ticket (since you added each of those) and open new tickets each time I find a missing affix? Or is it easier if I list all missing affixes in one thread and leave it open?

I think it's better if we keep this thread opened and post missing mods here.

> Also, are the filters on your app case sensitive? I can add filters in manually in between updates but not sure how careful I need to be when adding them.

Item names are not case sensitive, however mod names are case sensitive for performance reasons, so you have to be careful when adding them.

**Comment by licoffe** [comment]
I just added 82 new mods to the list using [poedb](http://poedb.tw/) I will post the file used for auto-completion later today if you want to try ahead of the next release.

**Comment by gdneye** [comment]
A couple more

"% increased Movement Speed during Flask effect" from Rotgut QS Flask
"% increased Area of Effect during Flask Effect" from Dying Sun Ruby Flask

TY

**Comment by licoffe** [comment]
I have to leave for several days, so I won't be able to update the tool while I'm away, but I'll do it when I return. In the mean time, you can add these affixes in the affix-completion.json file.

By the way, did the last release fix the issues you had with affix search?

**Comment by gdneye** [comment]
No problem on being away.  Thanks for all the work you've done to keep this program updated.  I haven't had any issues with searching since you pushed the last update so I think its good!

**Comment by licoffe** [comment]
You're welcome, I'm glad when people use my tools :) Thanks to you for finding all these bugs and quirks ;)

**Comment by gdneye** [comment]
"#% additional Block Chance" from the Reckless Defense Jewel.

Thanks!

**Comment by gdneye** [comment]
I may just be missing it but I can't figure out how to add an Item Quantity filter for maps.  Specifically to target higher Item Quantity Harbinger's maps.

**Comment by licoffe** [comment]
Thanks for the heads up! I'm currently reworking the whole affix UI [(Preview)](http://i.imgur.com/jpxDprg.png) to give a better user experience. I added the missing mods.

Item Quantity is a property (just like APS and crit) and can't be searched right now until I create the proper UI. I have sufficient space in front of the "Quality" and "Item level" fields to add a few more search fields :) Is it even possible to search for Item Quantity on poe.trade?

**Comment by gdneye** [comment]
You know what I'd never tried to search for Quantity before searching for Beachhead maps.  I don't see an option in poe.trade but poeapp allows it

https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4QALMaeWAOzxWhABoRaAzAewwg4GsUasAF4oAJhjaIsWAHJgAtkVIAVMigAEAIVwBjMmrCj1ACUrU6DdQFkwAB2Yhb0DrYYRY6DAElU89QEVEMBp3CABPEgBtEABWAAYHEABdAF8gA

That said, I know there is a balance between function and design.  Eventually, trying to fit every little feature into an app will make the interface bloated and this is somewhat of a lesser used feature.  If you end up deciding that it is not adding enough value for the space it takes up I'd understand.

**Comment by gdneye** [comment]
PS the new UI looks good and having those additional mods will be a very nice addition.

Thanks

**Comment by gdneye** [comment]
Found a couple more

- % reduced Charges (for flasks)
- All of the "A Master Seeks Help" affixes
e.g. You will find Zana and complete her mission. She will reward you with extra reputation and favour.

**Comment by licoffe** [comment]
> % reduced Charges (for flasks)

I currently have the following affixes "[Explicit] #% reduced Flask Charges used" and "[Unique explicit] #% reduced Charges used". Isn't one of them the same?

> All of the "A Master Seeks Help" affixes

These are prophecy texts so I didn't include them in the affix list, but I can add it as a new feature :)

**Comment by gdneye** [comment]
I'll test out  "[Explicit] #% reduced Flask Charges used" overnight tonight.

I was looking at
https://pathofexile.gamepedia.com/Flask#Prefix

where it states the affix is

(20 to 25)% reduced Charges used, 

but I've noticed before that the wiki is often out of date and I wouldn't be surprised if this is one of those cases.

**Comment by gdneye** [comment]
Since it has been quite a while since I have noticed any missing affixes I will close this in order to reduce clutter on the "Issues" page.  I will re-open if needed.
