### ISSUE TITLE
"Clear Filter" button

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#28]
The "Clear Filter" button resets league to "Harbinger Hardcore".  I am playing Harbinger Softcore so I have to reset this any time I use the "Clear Filter" button.  I think it would make most sense if the "Clear Filter" button leaves the league filter at whatever it was previously set at.

**Comment by licoffe** [comment]
Sure, makes sense :)

**Comment by licoffe** [comment]
It should be fixed in the last release :)
