### ISSUE TITLE
ChangeId not changing in filter mode

### ISSUE THREAD

**Issue by P4uLT** [licoffe/POE-sniper#29]
Hello,
Since the new update, i have an issue in filter mode.
The app get only one time the change id in filter Mode and after stay stuck on the change id.
In under pricemode, the change id is correctly renewed.

**Comment by licoffe** [comment]
Hi, could you check if it still happens when you disable "Show poe trade stats in the filters" in the settings?

**Comment by P4uLT** [comment]
I unchecked everything  in Misc. Same issue :/

**Comment by licoffe** [comment]
:( It's probably related to the filter setup. Would it be possible to send your "filters.json" file to my [mail address](mailto:p1lgr11m@gmail.com)? The file can be found in AppData\Roaming\POE-Sniper on Windows.

**Comment by P4uLT** [comment]
I cleaned it, and added new filters. Seems working at start, but stuck again.
All these filters have been imported by poe trade.

Json  filter : 

https://pastebin.com/Hkh4uKJf

**Comment by licoffe** [comment]
Ok, thanks! I'll tell you when it's fixed.

**Comment by P4uLT** [comment]
I saw some undefined value in js when importing some complex filter with affix value. Maybe it's linked. ( and btw i often have this bug with undefined).

**Comment by licoffe** [comment]
So, it's working on my side, but I modified the code since the last release, which probably fixed your issue. I'll publish a new patch soon.

**Comment by licoffe** [comment]
Just published a new version. Could you tell me if it fixes your issues?

**Comment by P4uLT** [comment]
Working better, Thanks :)
