### ISSUE TITLE
results is not showing

### ISSUE THREAD

**Issue by Xloctis** [licoffe/POE-sniper#3]
![image](https://user-images.githubusercontent.com/13437936/27172835-ffc30eec-51cf-11e7-95dd-64f064e6543a.png)

**Comment by licoffe** [comment]
Could you send me a copy of your filters.json file?

**Comment by Xloctis** [comment]
https://mega.nz/#!QuhTVB5J!vtrnFBIE6jBtCzR4cebWBKOc3eHCu52LHXxbN5l56Kw

**Comment by Xloctis** [comment]
[filters.zip](https://github.com/licoffe/POE-sniper/files/1077270/filters.zip)
FORGOT TO MENTION:
i've updated the files you uploaded 10 hours ago because with previous version i had a bug which was that somehow my 2 filters were linked or wtf, if i change one second one recieves save change, if i delete one both of them gets removed, but they will still be present when you restart sniper

**Comment by licoffe** [comment]
Thanks for the upload, I'll look into it a bit later.


> i've updated the files you uploaded 10 hours ago because with previous version i had a bug which was that somehow my 2 filters were linked or wtf, if i change one second one recieves save change, if i delete one both of them gets removed, but they will still be present when you restart sniper

Oh yeah that would be this [issue](https://github.com/licoffe/POE-sniper/issues/2). Did the last update fix that for you?

> also id enjoy a lot if you add me on discord or somewhere where we can discuss about this program a lil more (xloctis#8421)

I just added you :)

**Comment by licoffe** [comment]
I published a new release, could you try it and tell me if it fixes your issue?

**Comment by Xloctis** [comment]
remove issue
