### ISSUE TITLE
Unsure if certain affixes are working

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#30]
I set up some filters and ran the app overnight.  When I came back this morning the results didn't seem to make sense.

Out of 8 filters only one filter (Lion's Roar) provided any responses.  Responses for Lion's Roar came through consistently starting at 00:18:32 until 12:10:52.  In that time period there were 25 responses, spaced fairly evenly.  

In that same 12 hour time period none of the other 7 filters resulted in a single response and some of those filters were quite broad.

Lastly, if I search poeapp.com I see responses from that time frame that should have showed up.

https://youtu.be/o8UlUgldg1I

**Comment by gdneye** [comment]
Probably going to attempt a re-install... here is the filters.json file if it helps.

[{"league":"Harbinger","item":"Andvarius","title":"<span style=\"padding-right: 10px;\">Andvarius</span><span class=\"filter-affix\">( 50 - 80 )% increased Rarity of Items found</span>","budget":"","currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"22e547e2-a703-15f2-a484-242d17d8c640","corrupted":"false","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"#% increased Rarity of Items found":["50","80"]},"affixesDis":["( 50 - 80 )% increased Rarity of Items found"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"Any price"},{"league":"Harbinger","item":"Dying Sun","title":"<span style=\"padding-right: 10px;\">Dying Sun</span><span class=\"filter-affix\">( 0 - 10 )% reduced Charges used</span>","budget":"","currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"534d6a43-2547-d9dd-855b-70a4166cde38","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"( # - # )% reduced Charges used":[0,10]},"affixesDis":["( 0 - 10 )% reduced Charges used"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"Any price","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Goldwyrm","title":"<span style=\"padding-right: 10px;\">Goldwyrm</span><span class=\"filter-affix\">( 19 - 19 )% increased Quantity of Items found</span>","budget":1,"currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"de777476-f1a4-6406-5079-03bf651ecf7c","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"( # - # )% increased Quantity of Items found":[19,19]},"affixesDis":["( 19 - 19 )% increased Quantity of Items found"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"1 chaos","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Goldwyrm","title":"<span style=\"padding-right: 10px;\">Goldwyrm</span><span class=\"filter-affix\">( 20 - 20 )% increased Quantity of Items found</span>","budget":8,"currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"13e52758-7b0e-35f2-6c55-d05e2f4e329d","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"( # - # )% increased Quantity of Items found":[20,20]},"affixesDis":["( 20 - 20 )% increased Quantity of Items found"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"8 chaos","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Lion's Roar","title":"<span style=\"padding-right: 10px;\">Lion's Roar</span><span class=\"filter-affix\">( 25 - 25 )% more Melee Physical Damage during effect</span>","budget":25,"currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"777d182e-4c04-f691-35a3-bfac1a627ddd","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"#% more Melee Physical Damage during effect":["25","25"]},"affixesDis":["( 25 - 25 )% more Melee Physical Damage during effect"],"buyout":true,"clipboard":true,"itemType":"any","active":true,"checked":"checked","displayPrice":"25 chaos","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Taste of Hate","title":"<span style=\"padding-right: 10px;\">Taste of Hate</span><span class=\"filter-affix\">Gain ( 20 - 20 )% of Physical Damage as Extra Cold Damage during effect</span>","budget":200,"currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"1573f3bb-d107-cdd9-fa5f-e49c05571c44","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"Gain ( # - # )% of Physical Damage as Extra Cold Damage during effect":[20,20]},"affixesDis":["Gain ( 20 - 20 )% of Physical Damage as Extra Cold Damage during effect"],"buyout":true,"clipboard":true,"itemType":"any","active":true,"checked":"checked","displayPrice":"200 chaos","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Vessel of Vinktar","title":"<span style=\"padding-right: 10px;\">Vessel of Vinktar</span><span class=\"filter-affix\">Damage Penetrates (  -  )% Lightning Resistance during Flask effect, (  -  )% increased Charges used</span>","budget":"","currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"d3eb939e-2b43-0420-abc4-faad2b1d9320","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"Damage Penetrates (  -  )% Lightning Resistance during Flask effect":[null,null],"(  -  )% increased Charges used":[null,null]},"affixesDis":["Damage Penetrates (  -  )% Lightning Resistance during Flask effect","(  -  )% increased Charges used"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"Any price","link_min":"","link_max":"","poeTradeType":""},{"league":"Harbinger","item":"Vessel of Vinktar","title":"<span style=\"padding-right: 10px;\">Vessel of Vinktar</span><span class=\"filter-affix\">(  -  )% increased Charges used, (  -  )% of Physical Damage Converted to Lightning during Flask effect</span>","budget":"","currency":"Chaos Orb","links":"any","socketsTotal":"","socketsRed":"","socketsGreen":"","socketsBlue":"","socketsWhite":"","id":"a15b81fe-6ae7-a288-01df-0bade37c97dc","corrupted":"any","crafted":"any","enchanted":"any","identified":"any","level":"","tier":"","experience":"","quality":"","rarity":"any","armor":"","es":"","evasion":"","dps":"","pdps":"","affixes":{"(  -  )% increased Charges used":[null,null],"(  -  )% of Physical Damage Converted to Lightning during Flask effect":[null,null]},"affixesDis":["(  -  )% increased Charges used","(  -  )% of Physical Damage Converted to Lightning during Flask effect"],"buyout":true,"clipboard":false,"itemType":"any","active":true,"checked":"checked","displayPrice":"Any price","link_min":"","link_max":"","poeTradeType":""}]

**Comment by licoffe** [comment]
Ok, thanks for reporting! I'm looking into it. I identified a first issue already. When parsing item mods to compare with the filter, I'm storing all the mods (explicit, implicit, etc...) in an object. For items such as "Andvarius" which have both implicit and explicit "#% increased Rarity of Items found", this would cause the mod to be rewritten with the implicit value. So, when searching for 50-80 range, the value would always below or equal to 15. I changed the code, to sum up the values starting from now.

**Comment by gdneye** [comment]
I might suggest that the code only look at the explicit values instead of summing?  Typically the value of an object lies in the explicit as implicits can be easily and cheaply fixed with a Blessed Orb.

**Comment by gdneye** [comment]
I spoke too soon.  I have been unable to get the "increased physical damage taken" affix to work with the Abyssus helmet.  The filter below returns no responses, but removing the "increased physical damage taken" affix results in plenty of responses.

![image](https://user-images.githubusercontent.com/26702989/33684127-cdeed76a-da92-11e7-8460-7f652eaaf981.png)

**Comment by licoffe** [comment]
Thanks for reporting, I'll see what I can do :)

**Comment by licoffe** [comment]
I found the issue! It should be solved in the new version.
