### ISSUE TITLE
Javascript error on startup

### ISSUE THREAD

**Issue by bmtpowers** [licoffe/POE-sniper#31]
Whenever I try to start poe-sniper.exe, I get this error and it will not open.  It was working fine for me on 8/5-8/6, but hasn't worked for the past week or so.

Thanks for the great program.

![poe sniper](https://user-images.githubusercontent.com/9851687/29394111-e6815842-82cd-11e7-8155-78f21215e25b.png)

**Comment by licoffe** [comment]
Hi Ben, this issue happens when the config.json file becomes corrupted. You can delete the config.json file (in C:\Users\Ben\AppData\Roaming\POE-sniper) and it will fix the issue. It should no longer happen with the last version.

**Comment by licoffe** [comment]
Closing this issue since it's should not happen anymore
