### ISSUE TITLE
Occasionally the next_change_id times out

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#32]
I frequently leave this sniper and my whoops on overnight to help verify if I have a good idea of the value of an item.  I've noticed that occasionally the sniper will get caught in a loop and get stuck on the same next_change_id.  It isn't a significant problem as clicking "stop" then "snipe" resets the next_change_id and it will begin working again, but sometimes I'll be playing and realize that I haven't heard a ding in an hour or so when they usually come every few minutes.

Not sure if this is at all possible, but maybe there is a way to run an error check every once in a while.  If the next_change_id hasn't updated in 5 minutes maybe auto reset it?

One time it seems to always occur is on realm resets (I assume the river stops during the reset either bc nobody is posting new items or bc ggg turns it off).  Not sure if re-checking every 5 minutes would work for that bc realm resets are usually > 5 mins, but if it kept checking I guess it would eventually work.

**Comment by licoffe** [comment]
Any non-caught error might cause the program to stop working properly. I'll try running the indexer for an extended period of time and see if I can reproduce this issue.

**Comment by IeUDE** [comment]
I had this happen to me too.

For some reason, it stops, i.e. the ID stops changing. I can re-confirm this too because my internet usage drops way down the around 2k mega-bits . . .

**Comment by licoffe** [comment]
Do you both have this issue with the very last version?

**Comment by IeUDE** [comment]
Yes. Never tried the version before the latest.

**Comment by gdneye** [comment]
Yes, this error was occurring as recently as 1.3.6-fix2 (which was the latest version when you asked the question).  

I have not witnessed it happen yet on 1.3.7, but I will keep an eye out.
