### ISSUE TITLE
Wiki link opens 6 browser windows/tabs for the same item

### ISSUE THREAD

**Issue by Saiasanc** [licoffe/POE-sniper#34]
Title pretty much says it all. When I click the "wiki" link under a filter, it opens 6 separate tabs in by browser all pointing to the same item page on the wiki.  Here is a GIF showing the bug in action:

[![Screenshot from Gyazo](https://gyazo.com/70bbea1e86f91457b33830b0c16c0ece/raw)](https://gyazo.com/70bbea1e86f91457b33830b0c16c0ece)

**Comment by IeUDE** [comment]
I can confirm this.
