### ISSUE TITLE
poe.trade link should open in browser

### ISSUE THREAD

**Issue by Saiasanc** [licoffe/POE-sniper#35]
Currently the poe.trade link below a filter opens in a PoE Sniper window instead of an actual browser like the other links. Please correct this as right now you cannot interact with many of the site features within that window.

GIF:
[![Screenshot from Gyazo](https://gyazo.com/ebea181084850bb34eb849a11bb52c1a/raw)](https://gyazo.com/ebea181084850bb34eb849a11bb52c1a)

**Comment by licoffe** [comment]
Yes, I know this is a current limitation as I do not open a link but submit a form instead. I didn't really think about it yet, but this was planned. I'll work on this when I return on the 22nd.

**Comment by Saiasanc** [comment]
Completely understandable.  Something to think about when you get a chance to get into it.  You can still submit the form in the background. But instead grab the custom poe.trade link it returns and use that as the link that opens a browser window instead of having the link open that window it currently does.  Just a thought. Love the tool so far!

**Comment by licoffe** [comment]
This is trickier than it looks since poe.trade does not send back a link but the generated HTML instead.

**Comment by licoffe** [comment]
... but, it looks like we can extract it from the live search button link in the generated HTML output

**Comment by licoffe** [comment]
It works, the change will be effective in the next release.
