### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by Bomberchibbi** [licoffe/POE-sniper#36]
Hi Licoffe,

I tried out poesniper and so far I'm really loving it, here are some features I would love to see in a future release:

-ability to make filter groups like on poe trade with the and or sum count and so on conditions and maybe some improved logic like "if condition is met use filter group 2, else use filtergroup 3"

-searching for items that are already up for trade (not only live search)

- ability to organize my filters, the list should have an option to have expandable named folders and subfolders and the searches itself should be namable. That way instead of a giant filter name with all the conditions which are partly overlapping I could have a neat overview over what I'm searching

-update function via github

-ability to use the underpriced search in conjunction with filters, so far I can either search for my specified stuff with or without a set price, or I can search in general for underpriced stuff. What I would like would be the ability to set a filter like I do at the moment but instead of setting a buyout set the parameters of the underpriced search, so that I can search for specific Items that areunderpriced compared to the rest of the ones matching my filter.

**Comment by licoffe** [comment]
Hi Bomberchibbi,

Thanks a lot for the feedback and the new feature ideas! I am really glad that you like the tool :) 

Concerning the features, supporting advanced logic is something I've been considering. I started reworking affix edition in the last version and I'll try adding pseudo mods soon and some operators. 

Your second suggestion would require storing item information which is not the current approach of the tool, but an alternative way would be to use the poe.trade search link from the filter. It is currently in a beta state, but with proper rework it should allow you to search for existing items on Poe.trade. 

Your third suggestion is really interesting and it introduces some personal customization by the user. I really like this, I'll come back to you with some ideas I have on the matter. 

For your last suggestion, I suggest that you use the Poe.trade stats displayed under the filter which give you an idea of the current online price distribution for your item. This should help you get a better idea of the price.

**Comment by Bomberchibbi** [comment]
Hi Licoffe,

thanks for the reply, great to see that you like the suggestions. I forgot to add 2 other suggestions, one would be searching for open pre and suffix (it can even be done through poe.trade but is a hell of a lot of work with groupings) and the other is limiting the amount of pings per given time. What I mean by that is that right now it seems that poesniper is spam pinging for quite some time when I find several items at once, where id only want it to ping once for 5 items found within 5 seconds of each other.

Maybe some sort of "pause ping for x time after finding item" or something like that could fix that issue.

I really love this programm and I'd also like to help you out with it, so if there is something that I can help with or some way of talking to you live let me know about it.

**Comment by licoffe** [comment]
Hi Bomberchibbi,

Sure, we can talk on Discord if it's ok for you or on reddit. Same account name :)
