### ISSUE TITLE
Remove Filter Button - Bug

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#38]
The remove filter buttons have a couple of minor issues.

1) It seems as if it is not possible to remove the very last filter.  There are typically n - 1 red lines (where n is the number of filters).  Each red line matches up to a filter except the last one.  Clicking the general area where the red line should be results in an error message, "Windows cannot find '#!'. Make sure you typed the name correctly, and then try again."

2) The remove filter buttons do not seem to line up well with my mouse position.  It seems as if I have to be unusually high for it to hit the remove filter box and work.

**Comment by licoffe** [comment]
Thanks for reporting this! I think I had this bug at some point while I was updating my filters, but I didn't encounter it again. Would you have a screenshot of it?

**Comment by gdneye** [comment]
Hey Licoffe,

https://youtu.be/D14ArnljoW0

Sorry for the delay, just got caught up doing other stuff.

Here is a vid of the issue.  I think I've actually figured it partially out, but there are still some issues.

1) There are 3 red lines on the right and 4 filters.  There are consistently n-1 lines where n is the number of filters.  As I delete filters you can see this in action.  While its possible this was intentional on your part I doubt it as it seems most natural for the number of filters to match the number of red lines.
2) You can see (at 00:04) that the cursor appears to be offset.  The finger of the cursor is above the red line associated with the top filter, but the second filter is highlighted.
3) Upon clicking the top red line (at 00:08), the second filter is removed.
4) (at 00:14) I attempt to click the location where I expect the delete for the bottom filter to be and receive the following error message.  The message is received anytime I try to delete a filter but click in the incorrect place.

Apparently it is possible to delete them all (previously I was struggling to get the last one deleted.  Its possible that there was a change made in the latest version, but most likely I just didn't try enough last time.
