### ISSUE TITLE
Copy to clipboard not working - Linux

### ISSUE THREAD

**Issue by justanalias1** [licoffe/POE-sniper#39]
When clicking on a listed item the notification of the copied message shows in my corner as expected.
However neither CTRL + V nor middle mouse button pastes the message.
Seems like the text is not claimed at all.

Arch Linux x64
Xorg
Xfwm4 (from xfce4)

**Comment by licoffe** [comment]
Thanks for reporting! I'll try on a Ubuntu distribution to see if I can reproduce the bug there. I'm using a node module to copy strings to the clipboard and maybe it doesn't support Linux for some reason. I'll keep you posted.

**Comment by licoffe** [comment]
It seems that the node module I'm using (copy-paste) requires the **xclip** clipboard manager to be installed on Linux distributions. Could you check if it's installed on yours? 

https://www.archlinux.org/packages/extra/i686/xclip/

**Comment by justanalias1** [comment]
**xclip** was the missing dependency. After installing it works as expected.

Thank you alot and keep up the good work.
The Linux support is very appreciated.

**Comment by licoffe** [comment]
> xclip was the missing dependency.

Good to know, I added a note to the README :)

> The Linux support is very appreciated.

You're welcome! Electron really helps on that matter.
