### ISSUE TITLE
Feature Request - Option to clear certain results

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#40]
I have no idea how difficult this would be to code, but if it is not very difficult...

As I said in my last request I frequently leave the sniper on overnight to collect results and calibrate my understanding of the market in the morning.  Sometimes I wake up to 100+ results from one item (obviously I miscalculated on that item).

The ability to selectively clear certain items to clean up my results would be useful.  Maybe after applying a filter to results I could "Clear all filtered results" instead of clearing all?

Anyways, if its too difficult don't worry, but if its an easy add it would be useful.

Thanks as always.

**Comment by licoffe** [comment]
This is a really good idea and I wished I had this feature in numerous occasions :D It's not hard at all, I just have to put a tag for each entry specifying which filter found it and add a clear filter button on each filter to selectively remove all the tagged entries.

**Comment by licoffe** [comment]
Btw, do you still have the issue with the remove filter button?

**Comment by gdneye** [comment]
Glad to hear this is an easy addition, thanks!

**Comment by licoffe** [comment]
Implemented in the last commit :)
