### ISSUE TITLE
Unpriced item showed up as costing 0 chaos

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#41]
I had the "BO Only" option checked in the filter.

**Comment by licoffe** [comment]
Thanks for reporting, I'll see if I can reproduce the issue.

**Comment by licoffe** [comment]
I'm actually not sure if it's a bug. If BO only was on, then it wouldn't show unpriced item. Could it simply be somebody pricing the item for 0 chaos by mistake?

**Comment by xkomachi** [comment]
The same item showed up on poe.trade as unpriced, if that's any help. I think for most intents and purposes having a 0 currency b/o tag should be handled equivalently to unpriced items.
