### ISSUE TITLE
Not, Count, Sum, If - Feature Request

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#43]
Similar to poeapp and poe.trade it would be nice if we could include additional ways to include/exclude results.  Currently it is fairly difficult to search for good rares unless you have something very specific in mind.

As an example, I'm looking for two-toned boots with 30% ms and a high life roll.  I would like high rolls on res, dex or int but I don't care which.  In poe trade I would use the following affixes

**And**
(30 - 30)% increased movement speed
(90 - 124) to maximum life

**Sum (60 - )**
Dexterity
Intelligence
Fire Resistance
Cold Resistance
Lightning Resistance

I'm sure you already know how that all works so I won't explain any further for "Not", "Count" and "If", just wanted to make sure I gave at least one good example.

**Comment by licoffe** [comment]
Hi Gdneye,

I finally had time to work on this long requested feature and it will be released in the upcoming version.

[Here](https://streamable.com/0mco7) is a short video showing importation :)

**Comment by gdneye** [comment]
Wonderful, looking forwards to using this.  This was the last major reason I was still using poe.trade and poeapp.

Thanks!
