### ISSUE TITLE
[Bug - UI] Poe.Trade price overview does not warp correctly

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#46]
Demonstration pic:

![See attached image](https://user-images.githubusercontent.com/15238891/29742365-937223b4-8a86-11e7-9556-088e386fddda.png)

Might only happen when the window is small enough, I have yet to encounter this on full screen.

**Comment by licoffe** [comment]
It should be fixed in the last commit.

**Comment by xkomachi** [comment]
This is fixed, however the trash can icons stick to floating right when resizing, and obstruct the poe.trade text when the window is small enough. 

Related: https://github.com/licoffe/POE-sniper/issues/49

**Comment by licoffe** [comment]
Should be fixed in [commit b3d07a754bcf627fa3fdce1c8a14f5f4d10c0e6f](https://github.com/licoffe/POE-sniper/commit/b3d07a754bcf627fa3fdce1c8a14f5f4d10c0e6f)

**Comment by xkomachi** [comment]
Confirmed fixed, can be closed.
