### ISSUE TITLE
[Bug - UI, Windows] Socket and Socket Links are missing icons

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#47]
![links](https://user-images.githubusercontent.com/15238891/29742402-53c10cb6-8a87-11e7-904c-a918fed4295f.png)

Compiled from source - .exe did not have this problem.
Windows 7 SP1 (x64)
git version 2.12.0.windows.1
npm version 3.10.10

**Comment by licoffe** [comment]
Can you check the content of the web console ?

**Comment by xkomachi** [comment]
![links2](https://user-images.githubusercontent.com/15238891/29742876-cf178590-8a8f-11e7-9436-d97d8734e4d1.png)

The socket errors link to a media folder inside the app (i.e. app base folder/media/socket_str.png), which does not exist for me. I can share the log file if needed?

**Comment by licoffe** [comment]
The CSS issue is ok, it's due to loading poe.trade to extract stats. For the icons, the issue could be due to the way I write the path in the code. I always use "./media/socket_dex.png". You can try switching to "media\socket_dex.png", maybe it will solve this issue.

**Comment by xkomachi** [comment]
Sorry, I don't think I follow. Could you give more specific instructions for what you want me to do?

**Comment by licoffe** [comment]
Sorry, I was not really clear. I use UNIX paths in the program to link to ressources. It seems that when packaging for Windows, Electron handles the conversion to Windows paths. What you could try to do is to edit the function in the renderer.js file to use Windows paths.

**Comment by licoffe** [comment]
Could you try changing this "./media/socket_dex.png" to "media\socket_dex.png" in the renderSockets function?

**Comment by xkomachi** [comment]
Maybe I wasn't the one clear enough - it's unable to locate the folder because the folder doesn't exist. Here's the ls output in the app's compiled from source folder, and the one from an extracted release (app base folder\resources\app).

[release.txt](https://github.com/licoffe/POE-sniper/files/1253801/release.txt)
[source.txt](https://github.com/licoffe/POE-sniper/files/1253802/source.txt)

Taking the media folder from the extracted release and putting in the source folder solved the problem.

**Comment by licoffe** [comment]
Oh wow, ok! :D Looks like I didn't commit the media folder. That's silly, I will upload it right away!

**Comment by xkomachi** [comment]
I can confirm new git clones have the media folder after https://github.com/licoffe/POE-sniper/commit/7f32a47335e590867b55392d64163cab299706f4
Can be marked as resolved and closed imo.

**Comment by licoffe** [comment]
Ok, thanks!
