### ISSUE TITLE
[Bug - UI] Filter count does not update correctly.

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#51]
The following steps reproduced the problem for me:

1. Minimize the filters section.
2. Press 'add filter'.

Expected: The filter count goes up by 1.
Current: The filter count becomes 0.

Expanding the filter list and adding/removing any filter solves the issue.
Additionally, the console logs the following error: 

GET file:///C:/static/gen/packed_dark.css?f9a65ed1 net::ERR_FILE_NOT_FOUND (from renderer.js: 1178)

**Comment by licoffe** [comment]
This should be fixed now. Concerning the error, it appears when downloading poe.trade pages to extract prices. The pages expect a CSS file which is not present.

**Comment by xkomachi** [comment]
Fixed. Can you catch errors in the relevant section and ignore the error if it is this particular one?

**Comment by licoffe** [comment]
Yeah, I guess I could catch it and hide it since it doesn't impact anything anyway.

**Comment by licoffe** [comment]
Looks like this exception is on the browser side and can't be caught from within the code (see [link](http://www.webdeveloper.com/forum/showthread.php?306491-Catch-statement-error-code-not-executing&p=1377479#post1377479)). I'm closing this issue.
