### ISSUE TITLE
[Bug - Error] Error on clicking the trash icon next to a filter.

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#52]
Upon clicking the trash icon next to a filter, the following error pops up:

Windows cannot find '#!'. Make sure you typed the name correctly, and then try again.

The console logs "clearing" and shows no errors.

**Comment by licoffe** [comment]
This should be fixed in the last commit.

**Comment by xkomachi** [comment]
Doesn't result in an error anymore, but clicking it does nothing.  It's supposed to delete selected filters from what I can understand?

**Comment by licoffe** [comment]
It should remove the entries found by that filter from the list :)

**Comment by xkomachi** [comment]
Oh. Well, works :) Not totally related to this issue - I don't have a draft for it, but do you think further down the road being able to have fine control over individual filters is a goal of the project? I mean like your own code for importing/exporting filters; Being able to put filters in folders and add tags to a filter, then search, activate, or disable filters by their tag/location in the folder hierarchy; Defined interactions/priority lists for filters that are a subset of one another or potentially share results, etc.

**Comment by licoffe** [comment]
Sure, I actually had some other suggestions (see #36) regarding filter customization by the users. I guess for now, I will mostly focus on increasing stability/performances but after that sure. I really like the idea!
