### ISSUE TITLE
How to disable windows notifications?

### ISSUE THREAD

**Issue by enumag** [licoffe/POE-sniper#54]
For each result I first hear the sound notifications and half a second later a windows notification sound along with a message in bottom right corner:

![sniper](https://user-images.githubusercontent.com/539462/29881927-e2374380-8dab-11e7-8826-240050f19cd8.png)

I really do not need to be notified twice. And I also do not need the windows popup message since I have Sniper on different monitor than POE so I see everything anyway. How can I disable this behavior? I can't find this in settings.

I don't need a notification that a message was copied to my clipboard when I click an item either.

**Comment by licoffe** [comment]
Hi Enumag, I see what you mean. This is not possible right now, but I'll add an option in the settings to switch notifications off.

**Comment by enumag** [comment]
Looking forward to it, thanks!

**Comment by enumag** [comment]
I just disabled Windows notifications completely for now. So while this still would be nice to have it's not really a big issue.
