### ISSUE TITLE
A Master Seeks Help Prophecy

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#55]
The affixes for "A Master Seeks Help" do not populate.  I'm not sure if there are any other prophecies where the affix changes, but if there are I would guess the same issue exists for those prophecies.

https://youtu.be/BiOd9oLGtsA

Thanks

**Comment by licoffe** [comment]
The prophecy text was not getting added properly to the element. It should be fixed in the next version :) ([preview](https://imgur.com/ANFHlET))

**Comment by gdneye** [comment]
Thanks for adding this.  Just checked out the additions with the latest release (haven't had a chance to use them yet).  This is a huge update.  I'm excited to get home and test out all of the new features.

**Comment by licoffe** [comment]
I hope you'll have a smooth transition ;)
