### ISSUE TITLE
Issues using "#+ Maximum Frenzy"

### ISSUE THREAD

**Issue by MildPanda** [licoffe/POE-sniper#56]
When I click on the poe.trade link just to view its search terms it doesn't seem to properly select that mod. I have attached a picture of what the search term is. 
![chrome_2017-09-03_02-07-25](https://user-images.githubusercontent.com/5686244/30001775-dd65bdca-904c-11e7-92fd-e633f586c528.png)

Seems like it may be my issue? idk, seems a little confusing. I added the URL specific search query from poe.trade it it showed on the sniper "(implicit)" which seemed different and sure enough after I added maximum frenzy with the program it didn't have the "(implicit)" portion. Is there a way to do that? (picture of the difference shown bellow)
![poe-sniper_2017-09-03_02-11-47](https://user-images.githubusercontent.com/5686244/30001803-c0be7030-904d-11e7-94bc-1dd42b03636c.png)

**Comment by licoffe** [comment]
Hi Opzon, for now there is no real solution to this issue since I do not currently distinguish between implicit and explicit in the tool while poe.trade does.

**Comment by MildPanda** [comment]
Alright, well I will use the import feature to handle implicits, thanks for your work!

**Comment by licoffe** [comment]
I'm currently adding the possibility to choose between implicit, explicit, enchant and crafted mods ([Preview](http://i.imgur.com/jpxDprg.png)) so it should have a better compatibility with poe.trade in the next release.
