### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#57]
The new processing time feature is pretty cool (I'm also enjoying the improvements to the affixes).  I'm just wondering, is there a processing time that you would suggest I attempt to stay below in order to ensure that I am staying on top of the river?  Currently I am getting about 1ms of processing time per filter with no  filters appearing to be outliers.

From what I have researched, the POE trade API throttles requests to one per second (or 1000 ms).  Given the fact that there will only be one API request per 1000 ms my assumption is that I could get to a reasonable percentage of 1000 ms before needing to worry about falling behind on the river.  Would 200 ms of processing time be safe?  500 ms?  Currently I am only using about 20 ms of processing time, so either of those answer would represent a huge increase, but I think any understanding of the bottlenecks involved is likely to be useful to me.

Thanks!

**Comment by licoffe** [comment]
You should also take into account the transmission time of the chunk (which is not yet displayed). On my side, it takes from 2 sec to 30 sec in case of heavy API changes. If you see the changeID (the number near the "i" symbol) shift every 3 seconds you should be fine. A good way to know, is to compare the current changeID to the first set of digits from http://poe.ninja/stats. This website usually has one of the newest ids. I currently have 45 filters for a processing time of 50 to 100ms and the tool remains ahead of poe.ninja.

**Comment by IgorMCesar** [comment]
I have a similar question. I got 20ms with one filter, and poe.trade is always 1 min ahead of me. I live in Brazil, maybe thats the problem? Any ideas?

**Comment by licoffe** [comment]
@IgorMCesar How long does it take you to download chunks in average (how often do you see the changeID shift)? Also, could you compare your current ID with the one at [poe.ninja](http://poe.ninja/stats)?

**Comment by IgorMCesar** [comment]
@licoffe I think it changes after 4s~5s, the ID is sometimes ahead, others behind, i think...
![image](https://user-images.githubusercontent.com/5064518/30396895-7e2a9ea4-98a1-11e7-986d-a85b989f1a1d.png)

[EDIT]
Just checked, it starts ahead, stays ahead for 5 min and then it gets behind, from there is a downhill.
2 filters atm: 24ms

**Comment by licoffe** [comment]
Yeah, I have the same behavior at the moment. It takes between 3.5s to 5s to download a chunk of 1 MB which is ludicrous and I'm slowly falling behind. What happens is that the API currently has a very long Time to First Byte. Basically the majority of the time is wasted on waiting for the API to send back data, not downloading them. There's not much which can be done on your side.

**Comment by IgorMCesar** [comment]
Ok thx for the reply =). But some ppl report staying ahead of por.trade at least, thats not even my case. Poe.trade is faster :/

**Comment by licoffe** [comment]
It greatly varies with the location and depending on the hour. Right now I'm downloading a chunk every 2s average.
