### ISSUE TITLE
Life affix not showing up in results.

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#59]
![image](https://user-images.githubusercontent.com/26702989/30405455-9fe408e0-98b1-11e7-9154-4a1c493f3c71.png)

Life mods do not seem to be showing up.  The **onslaught spur two-toned boots** are showing up using a filter that requires 90+ life.  As you can see is appears to be showing all other mods fine, but no the life.

**Comment by licoffe** [comment]
Interesting! Could you show me the filter?

**Comment by licoffe** [comment]
Ok, I found out what happens. The T1 life mod on boots goes up to 89. The program is not able to match the affix tier and does not return anything instead of returning a `? +100 to Maximum Life`. I patched this and [it seems to work](https://imgur.com/4WkoMI4).

**Comment by gdneye** [comment]
That makes sense, I'll go ahead and close the issue.  If it happens again I'll re-open.

Thanks
