### ISSUE TITLE
[Issue] 30% Goldwyrm search not working

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#6]
Search for 30% Goldwyrm's not working...

https://youtu.be/MY12p6AQpq8

However, I did have previous results for 28% and 29% Goldwyrms.  So I checked the filters file and after parsing it in excel noticed that its formatting was somewhat different.  Not sure if that could be the issue.

https://youtu.be/xEyntNN2UNk

**Comment by licoffe** [comment]
I tried with some of my stuff as well. Sometimes it appears, sometimes it just won't. Not sure why this is happening. I'll investigate.

**Comment by gdneye** [comment]
Still running into this issue... No idea what is causing it.  I was able to search for Goldwyrm's without parameters, but adding a filter for Inc Quantity appears to cause it to stop working.

https://youtu.be/wfrCEOOXIJQ

**Comment by licoffe** [comment]
I'm sorry, I'm looking at your video but I don't understand what is wrong here...

**Comment by gdneye** [comment]
Oh wow... I am dumb.  

The app is replacing the old result with the new result.  I was expecting to see two pairs of boots in the results panel, but now that I rewatched the video I see that the old listing (2000c) is removed and replaced by the new listing (1900c).

That was my mistake, it looks like its working.

**Comment by licoffe** [comment]
No problem, glad we sorted it out :)
