### ISSUE TITLE
[Bug - UI] With an update log that is too long, the download or dismiss buttons are not visible.

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#62]
See attached image.
![pic-demo-1](https://user-images.githubusercontent.com/15238891/30481068-79967a36-9a25-11e7-97c8-f8944e7a10a4.png)

**Comment by licoffe** [comment]
Yeah, I figured it out already and [patched it](https://github.com/licoffe/POE-sniper/commit/04ed8a9329d0b61ddaca6f27c04fa1e374f22a17), but didn't released the code yet.
