### ISSUE TITLE
Slight delay between result and audio notification

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#67]
Beginning in the latest version of the app there is now a slight delay (<1 second) between the item appearing and the audio notification.  While not a huge delay, it seemed to be better (quicker) previously.  Was this delay added intentionally?

**Comment by chinhodado** [comment]
I noticed this as well

**Comment by licoffe** [comment]
There's a default delay of 5s between notifications so that they don't stack up. You can set the delay to 0 if you wish in the settings ("notification duration").

**Comment by gdneye** [comment]
Thanks, solved the problem!
