### ISSUE TITLE
Min Price

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#68]
Changelog for latest version states that you can set a min and max price, but I am unable to figure out how to set a min price.

![image](https://user-images.githubusercontent.com/26702989/30571671-f0028ddc-9cae-11e7-8d8e-efaf140c244b.png)

**Comment by licoffe** [comment]
I added this feature in the underpriced mode only. Do you think it would be useful in filter mode as well?

**Comment by gdneye** [comment]
I see, that explains why I couldn't find it. Ok, so my issue comes from results listed for zero (of whatever currency).I can only think of two situations where it has been an issue. First, if you don't set a Max price on an item the "bo only" feature doesn't seem to work and will return results listed for zero. There is a similar problem with poe.trade so I assume it is a result of the way the data is presented in the API. I've always just worked around this issue by setting an extremely high Max price. The second instance where this has been a problem is buying currency. It seems that a lot of people set currency to zero (or maybe it's an API issue when they don't set a specific price), so I get a lot of useless results for currency selling at zero.

So it's not really a situation where a "min price" is useful, it's more that a "don't show zero 'currency' results" would be useful.

I see a trade-off between these two solutions. "Don't show zero currency results" could be placed in the settings and save ui space, but having a min price encompassed "zero" results and could have additional uses I'm not thinking of.  If you were going to use ui space anyways adding a "min price" would seem to be the way to go.

**Comment by gdneye** [comment]
Hey Licoffe,

I logged in to your sniper to do some pre-3.1 testing and noticed that my currency filters are no longer returning currency that is unpriced.  I'm not sure if you intentionally fixed this in one of your updates or if it is an unintended consequence of some other change you made, but this now appears to be working properly.

Thanks,
Gdneye
