### ISSUE TITLE
Prices for specific uniques

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#71]
Hey Licoffe,

This is unrelated to your POE-sniper project, but I'm trying to figure out how to solve a problem and you've been a nice guy/seem to be interested in this kind of thing.  Basically, I'm looking to automate the process of finding price inefficiencies in POE.  Here is an example to illustrate what I've been able to figure out and where I'm running into problems.  Sorry if I over-explain, just want to make sure we're on the same page.

**What I've been able to figure out**
Say I wanted to look at the odds of getting a +1 Arrow on Drillneck.  In order to determine if there is a price inefficiency (and how large the inefficiency is), I need to...

Step 1 - Get the corrupted mod list (http://poedb.tw/us/mod.php?cn=MapFragment#Quivers) or here (https://pathofexile.gamepedia.com/List_of_item_corrupted_mods).  

Step 2 - Looking at those sites shows that there are 9 total corruption mods that can roll on a Drillneck.  Our desired mod is lvl 1, 4 other mods are lvl 1 and 4 mods are lvl 50-58.

Step 3 - There are two ways to increase our odds of getting +1.  #1 is to turn in "The Fletcher" on a low level character.  #2 is to buy a <ilvl 50 Drillneck to corrupt.  It is also possible that corrupting a normal (ilvl > 50) Drillneck would be profitable, so there are 3 total scenarios to examine.

Step 4 - In all 3 scenarios I need to know (a) the cost (cost of fletcher/cost of drillneck plus additional costs (vaal orbs, armourer's/blacksmith's scraps, jeweller's, fusings, blessed's) (One vaal to corrupt a drillneck, no additional costs for the flether); (b) the odds of +1; (c) the expected sale price of my +1 corruption; (d) the expected sale price of the various bricked corruptions.

Currently, poe.ninja provides me the cost of "the fletcher", the cost of a normal, non-corrupted  drillneck and all of my "additional costs"/currency costs.  I am also capable of calculating the odds of the various corruptions (and adjusting those odds for low-level drillnecks and/or the fletcher cards).  Also, excel now has api integration, so I can pull all of those values directly into excel, build formulas off of them, and automatically update the values with (literally) a single click of a button.

**Example**
Turning in "The Fletcher" Cards with a character below lvl 50 you have the following mods.
- Chaos Res (normally 5.88%, now 44.44%)
- Phys Dmg to Fire (normally 1.47%, now 11.11%)
- Phys Dmg to Cold (normally 1.47%, now 11.11%)
- Phys Dmg to Light (normally 1.77%, now 11.11%)
- Additional Arrow (normally 2.94%, now 22.22%)

**What I haven't been able to figure out**
As a result of all of this, I basically am left with one piece of the formula missing.  I need a way to automate the value of my various corruptions.  In other words, what is the Additional Arrow corruption worth?  What are the other corruptions worth?  I can look them up right now, but ideally I could set up the excel file to automatically find that value and update it and the relative formulas.

**Idea #1**
I'm pretty sure I can get excel to read the HTML from a website.  I should be able to set up excel to go to a given poe.trade link, pull down the first few values and average them (I can probably even remove outliers) to get a value.  This has a couple of potential drawbacks.  For one, I can't imagine it is nearly as efficient as an api link.  There is probably a _lot_ of manual work involved in this one.

**Idea #2**
There might be a source that I am unaware of that I could use to get this data.  Your poe-rates website actually seems pretty close.  This post is (partially) a feature request for that site.  I think that site is pretty much already set up to do this, I would just need to be able to add certain modifiers (adds an additional arrow in this case).  I'm also curious if poe-rates has an api set up.  Alternatively, since you've done a lot of research in this area, you might know somewhere else that I could pull this data.  If you know of any other websites that provide api information (similar to poe.ninja) I'd be happy to look through them and see if they can (at least partially) solve my questions.

**Comment by licoffe** [comment]
On top of my head, what I could do is setup a page which would extract, out of the Poe.trade search link, the results from Poe.trade and format them back to JSON or some other format for you. So ideally you would just have to pass the Poe.trade search address as a parameter to a specific page on  my website and it would return you clean data. I already have the codebase to do that in Poe-sniper so it shouldn’t take too long to setup. What do you think?

**Comment by gdneye** [comment]
I think that would work great.  Since I haven't done anything like this before I'm not exactly sure how it would work, but I feel pretty confident I could get it to work if you are willing to do that.

**Comment by licoffe** [comment]
So, I setup the API and you can access it at this address :)
http://poe-rates.com/actions/getPoeTradeStats.php

A call to the API takes two parameters:
- league
- poe.trade search ID
![untitled 3](https://user-images.githubusercontent.com/17992001/31272227-81bf6b6c-aa8a-11e7-8e2d-9d2ae792760f.png)

The reason why you have to specify the league is because I need to pull currency price conversions to chaos from poe-rates.

Here is a search example for +1 arrow drillnecks in Harbinger league:
http://poe-rates.com/actions/getPoeTradeStats.php?league=Harbinger&search=ausikumebutoni

The API results has the following format:

    { 
        data: [ 
            { seller: 'Sv_PvM', price: '5.8', currency: 'exalted', chaosPrice: 551 }, 
            { seller: 'Stratadiablo', price: '5.8', currency: 'exalted', chaosPrice: 551 }, 
            ...
         ], 
        quantity: 29, 
        min: 551, 
        max: 2185,
        mode: 665, 
        median: 712.5, 
        mean: 1300.84 
    }

where: 
- data is an array of objects. Each object has the seller name (_seller_), the original price (_price_), the original currency (_currency_) and the converted price to chaos (_chaosPrice_). I included this so that you can plot the price distribution if you wish
- quantity is the amount of items used for statistics
- min is the minimum price in chaos
- max is the maximum price in chaos
- mode is the most current price in chaos
- median is the central price in chaos of the distribution
- mean is the mean price in chaos of the distribution

I didn't really experiment with other poe.trade searches so it may be require some fixing. Tell me if you encounter any issue.

**Comment by gdneye** [comment]
Hey Licoffe,

First off, this is awesome, thank you very much.

I'm having some trouble getting the data into a table and I'm not sure why.  Attached is a video where I show a comparison of working with the POE.Ninja API vs working with the POE-Rates API.  With both APIs I am following the same basic steps.

https://youtu.be/glSkV0MrjLA

1) Open Excel
2) Use the Power Query Add-In to create a new web Query (Data>New Query>From Other Sources>From Web)
3) Enter the API URL and click "OK"
4) Use the Query Editor to Drill Down/Navigate
5) Generate a Table
6) Remove Unneeded Columns
7) Close and Load to Excel

With POE-Ninja these steps result in a formatted table.  With POE-Rates I am getting a table too, but one of the fields contains raw JSON (where I am expecting to have a _list_ or a _record_ that can be drilled into to get a formatted table).

With the exception of this problem, this is exactly what I was hoping for.

Thanks!
Gdneye

**Comment by licoffe** [comment]
Hey gdneye,

There was an issue with string escaping which probably caused the JSON content not to be recognized. I believe this is fixed now. Let me know how it works out for you :)

**Comment by gdneye** [comment]
I still seem to be having problems.  It is possible the issue is on my end, but I'm not having any luck figuring out what I might be doing wrong.  I see a couple of error messages that might shed light on the issue.

https://youtu.be/rcAZRheMygk

First, when I import from the API Excel is still treating it as a "Document" rather that loading straight into a table as it does with poe.ninja.

Second, when I go to web view Excel gives an error that "Table highlighting is disabled because this page uses Internet Explorer's Compatibility Mode."

Last, if I attempt to use the "Parse JSON" command in Power Query it gives me an error message stating that "We found extra characters at the end of JSON input.  Details: Value= Position=20"

Do any of those errors give you any insight into what the problem might be?

**Comment by licoffe** [comment]
I checked my JSON formatting using https://jsonlint.com/, https://jsonformatter.curiousconcept.com/ and https://codebeautify.org/jsonvalidator and it turned out to be valid in each of these tools. There must be some extra requirements for Power Query that I am not aware of. Could you send me a link to the poe.ninja api you use? It will help me understand what needs to be changed on my side to make it compatible with Power Query.

**Comment by gdneye** [comment]
OK I have good news and somewhat bad news.

The good news is that I was able to solve the problem.  The somewhat bad news is that I solved it entirely by luck so I can't really explain why it worked, but I can provide a couple of youtube videos showing what I did.  Here is the first one, using 

http://cdn.poe.ninja/api/Data/GetUniqueAccessoryOverview?league=Harbinger

https://youtu.be/H0uo8QIOGFw

And this video shows how I was able to get it to work with 

http://poe-rates.com/actions/getPoeTradeStats.php?league=Harbinger&search=ausikumebutoni

https://youtu.be/U76MAju3V5I

Again, I'm not sure why the poe.ninja api is being immediately interpreted as a table while I have to take a few steps to get your api interpreted that way, but it is working and that is what really matters!

Thanks again!
Gdneye

**Comment by gdneye** [comment]
Hey Licoffe... I've made some more progress on my project and got to the point where I wanted to plug some searches in and test them out.  I tested with a few searches and ended up getting the same API response from all searches.  Here are some example API calls...

http://poe-rates.com/actions/getPoeTradeStats.php?league=Harbinger&search=obakabarorubam
http://poe-rates.com/actions/getPoeTradeStats.php?league=Harbinger&search=amomanurimikou
http://poe-rates.com/actions/getPoeTradeStats.php?league=Harbinger&search=ubiwohahiherom

All three calls resulted in the same response.  I also tested those URLs on a different computer and received the same response.  I believe the API might be providing the original +1 drillneck data that you tested it with (although I can't be sure as I don't still have that information available).  My guess is that you set it up with a static result when you were building/testing the API and that it is still returning that static result.

Can you test those 3 URLs to see if you are getting the same response from all 3?

Thanks,
Gdneye

**Comment by licoffe** [comment]
Hi gdneye,

> All three calls resulted in the same response.

Yes, sorry for that. I was serving the wrong output file 🙄  It's working now, I checked with the three links you provided.

**Comment by gdneye** [comment]
Hey Licoffe,

Thanks for the fix, and it was working for a few days, but now I am getting no response when I go to those sites.  The same ones I linked previously are each giving no response.  I also tried a couple of new ones just to be sure.

Thanks!

**Comment by licoffe** [comment]
Hi gdneye,

It looks like it's working fine for me at the moment. Could it be a temporary issue with poe.trade?

**Comment by gdneye** [comment]
Hmm, sorry about that it does appear to be working fine for me now as well.  Maybe it was a poe.trade thing or maybe I had some issue.  Thanks for looking.
