### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#74]
Hi Licoffe,

It looks like your updates have been slowing down, but I've seen that you are still talking with xkomachi, so I'm assuming that you were still working some on this project.  If you are done just let me know and I won't make any more requests, but I have two requests that I don't believe would be difficult to implement, but would be pretty useful.

1 - Would it be possible to add a blacklist based on username?  For many of the items I search for there are some users who are clearly price-fixing.  I think there could be two approaches to the blacklist.  (A) Block the blacklisted account entirely or (B) Adjust the way the app responds to a blacklist (I would suggest no sound, no copy to clipboard, and possibly showing up in a different color).  My preference would be (B).

2 - Is it possible to add a maximum item level?  For corrupting some items (like Drillnecks) there is a benefit to having a lower ilvl and no downside.

Thanks,
Gdneye

**Comment by licoffe** [comment]
Hi Gdneye,

I’ve been taking a break lately for personal reasons. Regarding your requests: 

1: I’ve had 2 previous requests regarding this and I like both of the approaches you proposed :)

2: I’m thinking about a way to let users input additional information in the text field without having to modify the interface. Examples: <= 1, > 1, 1-34, etc... What do you think?

**Comment by gdneye** [comment]
No worries on the personal break, obviously this is something you are doing for free and  you owe us nothing.  I hope its nothing too serious or that if it is things get better soon. 

As for your suggestion on adding a way to add information without adding to the interface, I love the idea.  I feel like with a project like this one issue you are bound to run into is that every user will want different additions.  Some of those additions (such as a max ilvl) will only be useful in a very limited number of cases.  Finding a way to add those features that does not clutter up the interface is valuable and I think your suggestion does that very well.

**Comment by licoffe** [comment]
So, I implemented the blacklist feature. You can watch a quick video [here](https://www.youtube.com/watch?v=ubZFsvfDSmE&feature=youtu.be) showing how it works. The feature has been published in the last version of the tool.

I also implemented the operators (see [video](https://www.youtube.com/watch?v=YFn1K_QcJ1w)). I really like this idea in the end since it prevents cluttering the interface.

**Comment by gdneye** [comment]
Awesome, thanks for the additions!  I noticed the blacklist immediately and added a couple of obvious price fixers.  Hadn't noticed the operators so i'll check those out and try them.

**Comment by licoffe** [comment]
Operators are not yet in the last version, but I will publish a new one tomorrow including this feature :)
