### ISSUE TITLE
Explicit: Adds # to # Lightning/Fire/Cold to Attacks

### ISSUE THREAD

**Issue by pyrophobya** [licoffe/POE-sniper#75]
Seems it cannot find items with these mods.

**Comment by licoffe** [comment]
I just tried to setup a filter with the _Ring_ type and _Adds # to # Cold Damage to Attacks_ and it seems to work fine.

![cold](https://user-images.githubusercontent.com/17992001/32838533-82f50630-ca11-11e7-86cc-9b81c54e60d3.png)

There seems to be an issue with editing affixes with the # to # format (#66) and that may be causing the issue you're encountering. I'll look into it.

**Comment by pyrophobya** [comment]
Okay, I'm doing this with Explicit: Adds # to # Lightning damage to Attacks.
https://gyazo.com/d2fbd557fe7d1d398b416609ce793f8a
Seems when i click the poe trade link i only get items with Elemental Damage with Attack Skills ignoring the Lightning Damage to Attacks.
This is the Search i Imported in the Tool.
http://poe.trade/search/osayeonazokino

**Comment by licoffe** [comment]
Looks like I fixed it : [video](https://streamable.com/kc0j0). The fix should be active in the next release.

**Comment by pyrophobya** [comment]
Nice!

**Comment by licoffe** [comment]
I just uploaded the last version of the tool, could you tell me if it fixed the issue?

**Comment by pyrophobya** [comment]
I just tested with all 3 elements to attacks and its fixed.Nice job.

**Comment by licoffe** [comment]
Perfect! :)
