### ISSUE TITLE
Show image in filter

### ISSUE THREAD

**Issue by chinhodado** [licoffe/POE-sniper#77]
I don't know how feasible this is, but it would be nice to show the image of the item in the filter list, so that I can quickly find a filter at a glance. This is a nice QOL thing that would help a lot when you have dozens of filters.

**Comment by licoffe** [comment]
Sure, that's a good idea! Something like this?

![filter-picture](https://user-images.githubusercontent.com/17992001/33372232-85bb201a-d4fd-11e7-91f8-46702d255192.png)

**Comment by licoffe** [comment]
The last release now has filter icons

**Comment by chinhodado** [comment]
Awesome, thank you!
