### ISSUE TITLE
How can I save all my filters stored in your app? If my PC needs to be restored I would lose every filter I made!

### ISSUE THREAD

**Issue by ghost** [licoffe/POE-sniper#80]

**Comment by licoffe** [comment]
There is currently no option to import/export but you can backup AppData\Roaming\POE-Sniper to save the settings, filters, categories and blacklist.

**Comment by ghost** [comment]
Thx man

**Comment by Morgoth92** [comment]
Sorry man, I can't find the folder you are talking about, can you be more accurate? Thx
