### ISSUE TITLE
Sniper not working anymore

### ISSUE THREAD

**Issue by ghost** [licoffe/POE-sniper#83]
Suddenly, after the customization.json file was corrupted and restored i cannot see item results anymore. It seems like the public API is not recognized or loaded because the serial number is not shown. I love your app, pls help :(

**Comment by licoffe** [comment]
Sorry for that! I had to schedule a restart of the indexing and stats backend to take into account the new leagues and it probably locked the service sending the chunks to clients. I’ll take a look.

**Comment by licoffe** [comment]
Apparently GGG had an issue with their API for the last two hours.

**Comment by ghost** [comment]
Nvm, solved

**Comment by licoffe** [comment]
It should work fine now, there was an issue on my backend.

**Comment by kealsera** [comment]
@licoffe 

I am currently unable to find anything with the filters I've set up - I had no troubles with the exact same filters yesterday.
The same filters do work on poe.trades live search.

**Comment by licoffe** [comment]
Since Saturday, there are too many users pulling data from my backend which slows transfer speed for everyone.

**Comment by bolern** [comment]
its not working for me, dont even have the stash id showing for me

**Comment by ghost** [comment]
@licoffe 
It is not working again indeed :(

**Comment by licoffe** [comment]
Just came back from holidays, I’ll take a look at the issue tonight or tomorrow morning.

**Comment by licoffe** [comment]
@Morgoth92 I released a new version which should fix the issue.
