### ISSUE TITLE
Unable to select Abyss League

### ISSUE THREAD

**Issue by kealsera** [licoffe/POE-sniper#84]
Hey - is there anything I need to do in order to select Abyss as an League? Sniper is giving me only standard & Hardcore.

I grabbed your latest Win Release.

Best regards & lucky drops

**Comment by licoffe** [comment]
Sorry, there was an issue with my indexer backend providing the chunks. It should be resolved within the next hour. Just restart the tool in 1 hour or so and you should have the "Abyss" league option available.

**Comment by kealsera** [comment]
Working again, thanks :)
