### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by leet0rz** [licoffe/POE-sniper#87]
I just downloaded the newest version, all I did was type tabula in the name bar and started searching with the snipe button, but no results in over 1 hour. Is this still working? Thanks!

**Comment by licoffe** [comment]
Hi asdf337,

Sorry for the issues you encountered. There are some stability issues with the service sending data to the clients, which may stop working eventually and needs to be restarted. This is a temporary situation and I'm working on a better system.

**Comment by leet0rz** [comment]
Just thought I'd report it in, how long will it be down for, I heard they might be shutting down the API for "private" indexers soon? Is that the reason for the troubles? Good luck!
