### ISSUE TITLE
Map Searching

### ISSUE THREAD

**Issue by ghost** [licoffe/POE-sniper#88]
Hi @licoffe ! I need to snipe the new map of war of the atlas! Are there new settings that allow you to only see result from war of the atlas and not previous expansion! Thx a lot man! I love your software so much! :D Still pretty good after API nerf :P

**Comment by licoffe** [comment]
The only way currently is to set the tier of the map individually. I’ll see what I can do after Christmas holidays but my priority right now is to finish rewriting the indexer to run on the backend side, sending only results to the clients, not the raw data. To do this I also have to revamp a significant part of the client, I.e. removing all the unnecessary processing out of the app.

**Comment by ghost** [comment]
You're great dude! Enjoy your merry Christmas! :D

**Comment by licoffe** [comment]
I added this feature in the online version of the tool :)

![screenshot](https://user-images.githubusercontent.com/17992001/35241983-9688e04a-ffb8-11e7-905e-6834f322761d.png)
