### ISSUE TITLE
Missed affix from sight...

### ISSUE THREAD

**Issue by TA2DF** [licoffe/POE-sniper#89]
(_Unique Explicit_) "**Blight has #% increased Hinder Duration**"

An example of an item containing that affix I mentioned: [Allelopathy Sorcerer Gloves](https://pathofexile.gamepedia.com/Allelopathy)

**Comment by licoffe** [comment]
Sure, I'll add it. Thank you for reporting.

**Comment by licoffe** [comment]
Added to the online version of the tool.

![screenshot](https://user-images.githubusercontent.com/17992001/35165960-847f4b88-fd50-11e7-8add-302de2a259ee.png)
