### ISSUE TITLE
Bug (Browser Tool) - "Conversion" selection box does not appear to be working

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#92]
See screenshot.  I was using the shown filter with "Conversion" unchecked, yet was still receiving results in various currencies.

![image](https://user-images.githubusercontent.com/26702989/35065018-7cce1dda-fb91-11e7-9704-9b07e25ac30e.png)

**Comment by licoffe** [comment]
Thank you for reporting, it should be fixed now :)
