### ISSUE TITLE
Feature Request - Improved Currency Parsing

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#93]
Hi Licoffe,

I have ran into some general issues with Currency trading, I thought it best to list them together as there may be overlap in solving these issues.

1) It is difficult to Buy Chaos with Exalted Orbs.  Something like 74 Chaos : 1 Ex is a normal conversion ratio.  As a result you would want to set the "Price" to ".0135135135 Ex".  The App and website appear to cut off at 2 decimals.  Requiring the ratio to be either .01:1 (100 C: 1Ex) or .02:1 (50 C : 1Ex).  The same problem would occur when trying to buy any 2 currencies where one currency is much larger than the other.

2) Even with currencies that are closer in size (such as Chaos : Jeweller), it can still be difficult to convert with the sniper tool.  In the two screenshots I have attached you can see that user "Unstoppable_Hero" is selling 330 jeweller's at a 1 : 11.2 ratio.  In the app this same sale shows up as selling for .09 Chaos, which could be anything from 1 : 10.6 (.0943) to 1 : 11.7 (.0854).  Currently I just follow up with the seller and have not had major problems, but would it be possible to get the exact ratio listed the way currency.poe.trade lists it.  

It seems like the root of problems (1) and (2) is rounding.  I'm hesitant to ask for 5 decimals (as would be necessary for proper Ex:Chaos conversion).  I certainly think it would clutter up the app if all numbers rounded at 5 decimals and I think there are very few cases where more than 2 digits are needed (and even fewer where 5 are needed).  Currency conversion is the only case i can think of where more than 2 decimals are needed.  Perhaps it would be possible to set the rounding on a per filter basis (with a default of 2 decimals).  Or another option would be to round to extra digits if the items is a currency item, and to round even further for large currency items.

![image](https://user-images.githubusercontent.com/26702989/35066159-4c2d4148-fb95-11e7-987a-eab9a1dd1cb0.png)

![image](https://user-images.githubusercontent.com/26702989/35066164-51c7b30e-fb95-11e7-9004-388821e44b8c.png)

**Comment by licoffe** [comment]
> another option would be to round to extra digits if the items is a currency item, and to round even further for large currency items.

That's the best option in my opinion, since it's very unlikely people will need that kind of precision for non-currency items and it doesn't require user interaction. Luckily the API has a flag (frameType 5) for currency items :) It looks like this now:

![screenshot](https://user-images.githubusercontent.com/17992001/35146255-bd2a43d4-fd0a-11e7-88ce-5f2124c842ab.png)

**Comment by gdneye** [comment]
Looks like it should work great.  I'll go ahead and close the ticket for now but I'll mess around with it over the next couple of days to test it out.

Thanks,
Gdneye
