### ISSUE TITLE
poe-rates.com/live/ not returning any results

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#94]
Hi Licoffe,

I pulled up the website to see if I could test the fix you made to the "Conversion" button.  I added some currency filters and ran them for a bit (see filters on screenshot).  After noticing that the filters were not returning results I pulled up the sniper app and compared them against each other.  The sniper app was showing results while the website was not.

As a final test I included a pretty generic search (Goldwyrm with no additional filters) and pulled up a search for Goldwyrm on poe.trade.  After a few minutes (and 4 results on poe.trade) I haven't received any on the website.

On a side note I'm glad to notice that you've made a number of updates recently.  Hopefully the website will qualify for whitelisting by GGG.

![image](https://user-images.githubusercontent.com/26702989/35169320-bdaa20a6-fd21-11e7-93fd-cfbcb09f29d8.png)

Thanks,
Gdneye

**Comment by licoffe** [comment]
Hi Gdneye,

I was tweaking the server side code to fix an issue preventing non-priced items to appear (still working on this issue). It should work fine again.

**Comment by gdneye** [comment]
Thought this might be the case.

Thanks!
