### ISSUE TITLE
[Request] Adding Damage, APS, Crit.strike, and Block

### ISSUE THREAD

**Issue by Medivha** [licoffe/POE-sniper#95]
Yeah that are really important stats that are missing.
It would be nice to add every missing stat thats avaiable at poe.trade or atleast the most useful ones

for example attack per seconds(aps) and crit strikes are very important for finding good weapons and ofcourse snipe.

thx

**Comment by licoffe** [comment]
You can search by these criteria (except block) on the online version of the tool (http://poe-rates.com/live)

**Comment by Medivha** [comment]
n1 but on the online version there is no import for poe.trade links ;P

**Comment by licoffe** [comment]
It’s now possible to import poe.trade links on the online version
