### ISSUE TITLE
Currency issues

### ISSUE THREAD

**Issue by escequi** [licoffe/POE-sniper#98]
I'm playing in Bestiary and i've run into 2 issues so far:
1. Currency values does not reflect their actual value in the league at all, as like for exemple i've set the value to be 1 alch max and it show trades asking for 2 chisels (which are 1:1 to alchs), or set it to 1 chaos max and it show trades asking for 100 alts (which are almost 10c, lol);
2. After a while the price filter seems to stop working, it starting showing all the trades that fulfill the filter except for the price (like i have a filter set for any T11+ map that costs at most a chaos, then after a while it starts showing every T11+ map regardless of price

**Comment by licoffe** [comment]
> Currency values does not reflect their actual value in the league at all, as like for exemple i've set the value to be 1 alch max and it show trades asking for 2 chisels (which are 1:1 to alchs), or set it to 1 chaos max and it show trades asking for 100 alts (which are almost 10c, lol);

I'm using my own API to get currency values. It was set to fetch min computed values but that seems to be wonky in some situations. I just set it to median instead which should be less volatile. You can see the latest rates for Bestiary [here](http://poe-rates.com/actions/getLastRates.php?league=Bestiary) representing the median traded value of currencies in chaos. This is equivalent to going on currency.poe.trade, scrolling to the center of the listing and looking at the price. Currently 1 alch is 0.6667 chaos, 1 chisel is 0.6 and 1 alt is 0.1.

![rates](https://user-images.githubusercontent.com/17992001/37565184-b6641eea-2aa4-11e8-8a85-24a62a5ee5fb.png)
![ctoal](https://user-images.githubusercontent.com/17992001/37565185-b67f38ba-2aa4-11e8-97d1-48556ea2fd18.png)
![ctoc](https://user-images.githubusercontent.com/17992001/37565186-b69763c2-2aa4-11e8-8d76-0b020de72a94.png)
![ctoa](https://user-images.githubusercontent.com/17992001/37565187-b6ae1248-2aa4-11e8-8e1d-7d8e31c10faa.png)

> After a while the price filter seems to stop working, it starting showing all the trades that fulfill the filter except for the price (like i have a filter set for any T11+ map that costs at most a chaos, then after a while it starts showing every T11+ map regardless of price

Let's see if you still run into this issue with the changes I made to the API.

**Comment by escequi** [comment]
Thanks for the fast reply; Unfortunelly the {2} issue is still happening, i think it's about half an hour in that it start occouring, relauching the program fix it until the next deadline :p

**Comment by licoffe** [comment]
Could you try setting up the same search on http://poe-rates.com/live and see if you have the same issue?

**Comment by escequi** [comment]
Sure, i have both opened right now and i'll let you know when/if it happens in the client to see if it also happens in the website, one thing tho is that the website is a bit different than the client (the UI atleast), and i've noticed that there has been 6 commits since the last release (which i'm using the release and not have compiled/run the source on my own)

**Comment by escequi** [comment]
Ever since i started using both, it never happened again, guess i can live with it occasionally bugging out (if it ever does it again)

**Comment by licoffe** [comment]
Ok, let's keep the issue opened and please feel free to post an update if it happens again. If it stops working, could you post a screenshot of http://poe-rates.com/actions/getLastRates.php?league=Bestiary as well? This is the API that the tools are using to get the last rates.

**Comment by escequi** [comment]
![image](https://user-images.githubusercontent.com/11319347/37855371-bf2e4532-2ecd-11e8-9ece-340c4ff1e196.png)

**Comment by licoffe** [comment]
Thanks for the update! I’ll see what I can do

**Comment by escequi** [comment]
I think this only happens if i have the "(include barter offers)", so that might be the issue right there
